sonarcloud back

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,6 +18,29 @@ jobs:
     steps:
       - checkout
       - sonarcloud/scan
+
+      - run:
+          name: Check SonarCloud Quality Gate
+          command: |
+            echo "Checking SonarCloud Quality Gate…"
+
+            PROJECT_KEY="$SONAR_PROJECT_KEY"
+
+            STATUS=$(curl -s -u "$SONAR_TOKEN": \
+              "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" \
+              | jq -r '.projectStatus.status')
+
+            echo "Quality Gate Status: $STATUS"
+
+            if [ "$STATUS" != "OK" ]; then
+              echo "❌ Quality Gate FAILED. Stopping build."
+              exit 1
+            fi
+
+            echo "✅ Quality Gate PASSED."
+
+
+      
       - run:
           name: Build and Push Backend Image
           command: |
