nocache

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,6 +32,15 @@ jobs:
               -Dsonar.organization="$SONAR_ORG" \
               -Dsonar.login="$SONAR_TOKEN" 
 
+      - run:
+          name: Check sonar-project file exists
+          command: |
+            echo "Current working dir:"
+            pwd
+            echo "Files in working directory:"
+            ls -al
+            echo "Contents of sonar-project.properties:"
+            cat sonar-project.properties || echo "sonar-project.properties not found"
 
           
       # - run:
